Always enforce cleanup on exit

diff --git a/halium-install b/halium-install
--- a/halium-install
+++ b/halium-install
@@ -102,6 +102,9 @@ export IMAGE_DIR=$(mktemp -d .halium-install-imgs.XXXXX)
 source $LOCATION/functions/distributions.sh
 source $LOCATION/functions/core.sh
 
+# Always enforce cleanup on exit
+trap clean_exit EXIT
+
 # Start installer
 echo "Debug: Chosen rootfs is $ROOTFS_TAR"
 echo "Debug: Chosen android image is $AND_IMAGE"
